/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class abra_NativeSemiGlobalAligner */

#ifndef _Included_abra_NativeSemiGlobalAligner
#define _Included_abra_NativeSemiGlobalAligner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     abra_NativeSemiGlobalAligner
 * Method:    align
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_abra_NativeSemiGlobalAligner_align
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
