/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class abra_NativeAssembler */

#ifndef _Included_abra_NativeAssembler
#define _Included_abra_NativeAssembler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     abra_NativeAssembler
 * Method:    assemble
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIII)I
 */
JNIEXPORT jint JNICALL Java_abra_NativeAssembler_assemble
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
