/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class abra_NativeAssembler */

#ifndef _Included_abra_NativeAssembler
#define _Included_abra_NativeAssembler
#ifdef __cplusplus
extern "C" {
#endif
#undef abra_NativeAssembler_MAX_READ_LENGTHS_PER_REGION
#define abra_NativeAssembler_MAX_READ_LENGTHS_PER_REGION 6L
#undef abra_NativeAssembler_CYCLE_KMER_LENGTH_THRESHOLD
#define abra_NativeAssembler_CYCLE_KMER_LENGTH_THRESHOLD 43L
#undef abra_NativeAssembler_MIN_CANDIDATE_BASE_QUALITY
#define abra_NativeAssembler_MIN_CANDIDATE_BASE_QUALITY 10L
/*
 * Class:     abra_NativeAssembler
 * Method:    assemble
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIIIDII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_abra_NativeAssembler_assemble
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jint, jdouble, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
